/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nodequeryclient;

import java.awt.Desktop;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.stage.Stage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLbl = new javax.swing.JLabel();
        updAccBtn = new javax.swing.JButton();
        setKeyBtn = new javax.swing.JButton();
        keyFld = new javax.swing.JPasswordField();
        enterAPIlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NmStaticLbl = new javax.swing.JLabel();
        tzStaticLbl = new javax.swing.JLabel();
        TzLbl = new javax.swing.JLabel();
        seperatorSep = new javax.swing.JSeparator();
        ShowAccStatsBtntgl = new javax.swing.JToggleButton();
        updServerDataBtn = new javax.swing.JButton();
        ShowServStatsBtn = new javax.swing.JButton();
        ShowServTBLbtn = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        GetStartedBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        NameLbl.setText("_____");

        updAccBtn.setText("Update Account Data");
        updAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updAccBtnActionPerformed(evt);
            }
        });

        setKeyBtn.setText("Set");
        setKeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setKeyBtnActionPerformed(evt);
            }
        });

        keyFld.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        keyFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyFldActionPerformed(evt);
            }
        });

        enterAPIlbl.setText("Please Enter your API key below");

        NmStaticLbl.setText("Name:");

        tzStaticLbl.setText("Time Zone:");

        TzLbl.setText("_____");

        ShowAccStatsBtntgl.setText("Show Account Statistics");
        ShowAccStatsBtntgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAccStatsBtntglActionPerformed(evt);
            }
        });

        updServerDataBtn.setText("Update All Server Data");
        updServerDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updServerDataBtnActionPerformed(evt);
            }
        });

        ShowServStatsBtn.setText("Show Server Statistics");
        ShowServStatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowServStatsBtnActionPerformed(evt);
            }
        });

        ShowServTBLbtn.setText("Show Server Table");
        ShowServTBLbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowServTBLbtnActionPerformed(evt);
            }
        });

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nodequeryclient/yHl8Myx1-thumb.png"))); // NOI18N

        GetStartedBtn.setText("Getting Started With NodeQuery");
        GetStartedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetStartedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(enterAPIlbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(keyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setKeyBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NmStaticLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tzStaticLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLbl)
                            .addComponent(TzLbl))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(updServerDataBtn)
                        .addGap(203, 203, 203)
                        .addComponent(ShowAccStatsBtntgl)
                        .addGap(18, 18, 18)
                        .addComponent(updAccBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(58, Short.MAX_VALUE)
                                .addComponent(ShowServStatsBtn)
                                .addGap(130, 130, 130))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(GetStartedBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(logoLbl)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowServTBLbtn)
                            .addComponent(seperatorSep, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updAccBtn)
                    .addComponent(ShowAccStatsBtntgl)
                    .addComponent(updServerDataBtn))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(enterAPIlbl)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keyFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setKeyBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLbl)
                            .addComponent(NmStaticLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tzStaticLbl)
                            .addComponent(TzLbl))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ShowServStatsBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(seperatorSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(ShowServTBLbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(GetStartedBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logoLbl)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        NameLbl.getAccessibleContext().setAccessibleName("lblName");
        NameLbl.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updAccBtnActionPerformed
        String Name = null;
        try {
            Name = DB.getFromAccDBString("TBLACCOUNT", "NAME", DB.getNumberOfRows()-1);
        } catch (SQLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        NameLbl.setText(Name);
        try {
            TzLbl.setText(DB.getFromAccDBString("TBLACCOUNT", "TIMEZONE", DB.getNumberOfRows()-1));
        } catch (SQLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updAccBtnActionPerformed

    private void setKeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setKeyBtnActionPerformed
       
        DB.setAPIkey(keyFld.getText());
        if (keyFld.getText().length()==48 && Main.isAllASCII(keyFld.getText())==true){
        
        Account ac7=new Account();
        try {
            ac7.getRequests();
        } catch (HTTPstatusException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ac7.InsertAccount();
        } catch (SQLException | HTTPstatusException | MalformedURLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ServerList sl=new ServerList();
        } catch (SQLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }}
        else{JOptionPane.showMessageDialog(null, "API Key must be 48 characters & must consist of only ASCII characters");}
        
    }//GEN-LAST:event_setKeyBtnActionPerformed

    private void keyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyFldActionPerformed

    private void ShowAccStatsBtntglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAccStatsBtntglActionPerformed
        AccountStats acstat=new AccountStats();
        //acstat.setVisible(true);
        //AccountStats.launch("");
        //acstat.showWindow();
         javafx.application.Application.launch(AccountStats.class);

        
    }//GEN-LAST:event_ShowAccStatsBtntglActionPerformed

    private void updServerDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updServerDataBtnActionPerformed
        Account acc6=new Account();
        
        try {
            try {
                if (acc6.checkSuccessfulResponse()==true){ServerList Serv1=new ServerList();
                Serv1.setServer();
                }
                else{JOptionPane.showMessageDialog(null, "API Key Invalid");}
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updServerDataBtnActionPerformed

    private void ShowServStatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowServStatsBtnActionPerformed
        javafx.application.Application.launch(ServerStats.class);
       
       
        
    }//GEN-LAST:event_ShowServStatsBtnActionPerformed

    private void ShowServTBLbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowServTBLbtnActionPerformed
        ServerData sd=new ServerData();
        sd.setVisible(true);
        
    }//GEN-LAST:event_ShowServTBLbtnActionPerformed

    private void GetStartedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetStartedBtnActionPerformed
        URL getstart = null;
        try {
            getstart = new URL("https://nodequery.com/help/getting-started");
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        openWebpage(getstart);
    }//GEN-LAST:event_GetStartedBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(
             javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
        
        
    }
    public static void openWebpage(URI uri) {
    Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
    if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
        try { 
            desktop.browse(uri);
        } catch (Exception e) {
            e.printStackTrace();
        } 
    } 
} 
 
public static void openWebpage(URL url) {
    try { 
        openWebpage(url.toURI());
    } catch (URISyntaxException e) {
        e.printStackTrace();
    } 
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetStartedBtn;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel NmStaticLbl;
    private javax.swing.JToggleButton ShowAccStatsBtntgl;
    private javax.swing.JButton ShowServStatsBtn;
    private javax.swing.JButton ShowServTBLbtn;
    private javax.swing.JLabel TzLbl;
    private javax.swing.JLabel enterAPIlbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField keyFld;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JSeparator seperatorSep;
    private javax.swing.JButton setKeyBtn;
    private javax.swing.JLabel tzStaticLbl;
    private javax.swing.JButton updAccBtn;
    private javax.swing.JButton updServerDataBtn;
    // End of variables declaration//GEN-END:variables

}
